POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyb25lcGVhY2UiLCJpZCI6IjVkYjAxNWY1YTllZWY3MDQ0YjgxNjQyZCIsImlhdCI6MTU3MTgzNzEyN30.t7WHRElCSDRg1sMIZDkTLyFD_sFhIyCHbe2CLM1ik_4

{
    "title": "To Ace Your Job Interview, Get into Character and Rehearse",
    "author": "Cathy Salit",
    "url": "https://hbr.org/2017/04/to-ace-your-job-interview-get-into-character-and-rehearse",
    "likes": 13
}