POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml0VGVjaCIsImlkIjoiNWRiMDM1MThlZWM2YmIwYWU0ZjU4OWEwIiwiaWF0IjoxNTcxODY1Mzk1fQ.voUuu4RLyD_PbMHzvtJdl4YAbXkGogdbIRwkZcxZm58

{
    "title": "Ikigai: The Japanese Secret to a Long and Happy Life",
    "author": "Thomas Oppong",
    "url": "https://medium.com/thrive-global/ikigai-the-japanese-secret-to-a-long-and-happy-life-might-just-help-you-live-a-more-fulfilling-9871d01992b7",
    "likes": 14
}